# Generated by Django 4.2.4 on 2023-08-13 19:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('gym_users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('297c547c-353a-4215-a188-516f0703d9c1'), primary_key=True, serialize=False, unique=True),
        ),
    ]
