# Generated by Django 4.2.4 on 2023-08-13 19:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('gym_users', '0002_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('6494fc90-09f0-4ef1-bae0-b6c503b186ee'), primary_key=True, serialize=False, unique=True),
        ),
    ]
