# Generated by Django 4.2.4 on 2023-08-26 21:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('gym_users', '0006_alter_user_email_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('02072539-ec6c-4b4f-a649-4bd0a0316eb5'), primary_key=True, serialize=False, unique=True),
        ),
    ]
