# Generated by Django 4.2.4 on 2023-08-26 22:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('gym_users', '0007_alter_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleclass',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='payments',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('d26325d4-b398-4866-aab4-f0165e217ab7'), primary_key=True, serialize=False, unique=True),
        ),
    ]
