# Generated by Django 4.2.4 on 2023-08-27 04:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('gym_users', '0009_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('814d2419-21a1-49da-8345-8f0a5de63d94'), primary_key=True, serialize=False, unique=True),
        ),
    ]
