# Generated by Django 4.2.4 on 2023-08-27 04:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('gym_users', '0010_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('48a7d1da-05ea-49a1-89b3-3c8e04934461'), primary_key=True, serialize=False, unique=True),
        ),
    ]
