# Generated by Django 4.2.4 on 2023-08-27 05:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('gym_users', '0012_contactform_alter_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactform',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('9a017694-887f-4814-b061-57a5b3022ba9'), primary_key=True, serialize=False, unique=True),
        ),
    ]
