# Generated by Django 4.2.4 on 2023-08-27 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_users', '0014_alter_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='father_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
