# Generated by Django 4.2.4 on 2023-08-27 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym_users', '0015_profile_father_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='bio',
            new_name='biography',
        ),
    ]
