# Generated by Django 4.2.4 on 2023-08-27 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_users', '0016_rename_bio_profile_biography'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='amount',
            field=models.BigIntegerField(null=True),
        ),
    ]
