# Generated by Django 4.2.4 on 2023-09-03 20:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_users', '0018_equipment_profile_address_profile_cnic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='cost',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='delivery_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 3, 20, 1, 58, 370247)),
        ),
        migrations.AddField(
            model_name='equipment',
            name='description',
            field=models.TextField(blank=True, default='h', null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='muscles_used',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='id',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gym_time',
            field=models.TimeField(default=datetime.datetime(2023, 9, 3, 20, 1, 58, 369417)),
        ),
    ]
