# Generated by Django 4.2.4 on 2023-09-03 21:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_users', '0019_equipment_cost_equipment_delivery_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='delivery_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 3, 21, 25, 46, 583955)),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gym_time',
            field=models.TimeField(default=datetime.datetime(2023, 9, 3, 21, 25, 46, 583157)),
        ),
    ]
