# Generated by Django 4.2.4 on 2023-09-05 11:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_users', '0021_alter_equipment_delivery_date_alter_profile_gym_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='delivery_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 5, 11, 13, 32, 160169)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gym_time',
            field=models.TimeField(default=datetime.datetime(2023, 9, 5, 11, 13, 32, 159337)),
        ),
    ]
