# Generated by Django 4.2.4 on 2023-09-06 06:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_users', '0022_alter_equipment_delivery_date_alter_profile_gym_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='bank_account_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='delivery_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 6, 6, 47, 14, 551460)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='cnic',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gym_time',
            field=models.TimeField(default=datetime.datetime(2023, 9, 6, 6, 47, 14, 550695)),
        ),
    ]
