# Generated by Django 4.2.4 on 2023-09-06 06:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_users', '0023_payments_bank_account_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='delivery_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 6, 6, 49, 21, 620869)),
        ),
        migrations.AlterField(
            model_name='payments',
            name='bank_account_number',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gym_time',
            field=models.TimeField(default=datetime.datetime(2023, 9, 6, 6, 49, 21, 620091)),
        ),
    ]
