# Generated by Django 4.2.4 on 2023-10-29 16:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_users', '0026_remove_profile_experience_remove_profile_gym_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='delivery_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 29, 16, 44, 29, 356514)),
        ),
    ]
