# Generated by Django 4.2.4 on 2023-11-19 05:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_users', '0031_remove_payments_bank_account_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='mobile_no',
            field=models.BigIntegerField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='payments',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='delivery_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 19, 5, 46, 7, 506212)),
        ),
    ]
