# Generated by Django 4.2.4 on 2023-11-19 05:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_users', '0032_payments_mobile_no_payments_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payments',
            old_name='amount',
            new_name='paid_amount',
        ),
        migrations.AlterField(
            model_name='equipment',
            name='delivery_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 19, 5, 49, 24, 862205)),
        ),
    ]
