# Generated by Django 4.2.4 on 2023-11-19 08:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_users', '0033_rename_amount_payments_paid_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payments',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='delivery_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 19, 8, 28, 35, 920099)),
        ),
    ]
