# Generated by Django 4.2.4 on 2023-11-19 08:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_users', '0034_payments_end_time_payments_start_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduleclass',
            name='user',
        ),
        migrations.AlterField(
            model_name='equipment',
            name='delivery_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 19, 8, 46, 35, 789948)),
        ),
    ]
