# Generated by Django 4.2.4 on 2023-11-19 12:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_users', '0035_remove_scheduleclass_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payments',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='payments',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='scheduleclass',
            name='time',
        ),
        migrations.AddField(
            model_name='scheduleclass',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scheduleclass',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='delivery_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 19, 12, 18, 51, 191927)),
        ),
    ]
