# Generated by Django 4.2.4 on 2023-11-20 16:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_users', '0036_remove_payments_end_time_remove_payments_start_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payments',
            name='Address',
        ),
        migrations.RemoveField(
            model_name='payments',
            name='city',
        ),
        migrations.RemoveField(
            model_name='payments',
            name='mobile_no',
        ),
        migrations.RemoveField(
            model_name='payments',
            name='name',
        ),
        migrations.RemoveField(
            model_name='payments',
            name='province',
        ),
        migrations.AlterField(
            model_name='equipment',
            name='delivery_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 20, 16, 28, 44, 531376)),
        ),
    ]
