# Generated by Django 4.2.4 on 2023-11-21 06:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_users', '0038_scheduleclass_trainer_alter_equipment_delivery_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payments',
            name='total_amount',
        ),
        migrations.AlterField(
            model_name='equipment',
            name='delivery_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 21, 6, 25, 26, 956066)),
        ),
        migrations.AlterField(
            model_name='payments',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
