# Generated by Django 4.2.4 on 2023-11-21 06:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_users', '0039_remove_payments_total_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='biography',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='location',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='modified_at',
        ),
        migrations.AlterField(
            model_name='equipment',
            name='delivery_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 21, 6, 39, 39, 423292)),
        ),
    ]
