# Generated by Django 4.2.4 on 2023-11-21 13:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_users', '0040_remove_profile_biography_remove_profile_is_deleted_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='muscles_used',
        ),
        migrations.AlterField(
            model_name='equipment',
            name='delivery_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 21, 13, 32, 4, 720905)),
        ),
    ]
