# Generated by Django 4.2.7 on 2023-12-02 14:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_users', '0041_remove_equipment_muscles_used_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scheduleclass',
            old_name='name',
            new_name='class_name',
        ),
        migrations.AlterField(
            model_name='equipment',
            name='delivery_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 2, 14, 17, 22, 207616)),
        ),
        migrations.AlterField(
            model_name='payments',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(blank=True, choices=[('TRAINER', 'TRAINER'), ('user', 'USER')], max_length=255, null=True),
        ),
    ]
